function Y = ybus()  % Returns Y
%         |  From |  To   |   R     |   X     |     B/2  |  X'mer  |
%         |  Bus  | Bus   |  pu     |  pu     |     pu   | TAP (a) |
linedata =  [1      2       0.003125     0.029452      0.0        1
             3      4       0.003125     0.029452      0.0        1
             2      3       0.003125     0.029452      0.0        1];
linedata =  [1      2       0.01125/2     0.01125      0.0        1
             3      4       0.003125     0.0029452      0.0        1
             2      3       0.003125     0.0029452      0.0        1];
% Transformer X = 0.01125 
fb = linedata(:,1);     % From bus number...
tb = linedata(:,2);     % To bus number...
r = linedata(:,3);      % Resistance, R...
x = linedata(:,4);      % Reactance, X...
b = linedata(:,5);      % Ground Admittance, B/2...
a = linedata(:,6);      % Tap setting value..
z = r + 1i*x;            % Z matrix...
y = 1./z;               % To get inverse of each element...
b = 1i*b;                % Make B imaginary...
nb = max(max(fb),max(tb));    % no. of buses...
nl = length(fb);           % no. of branches...
Y = zeros(nb,nb);        % Initialise YBus...
 
 % Formation of the Off Diagonal Elements...
 for k = 1:nl
     Y(fb(k),tb(k)) = Y(fb(k),tb(k)) - y(k)/a(k);
     Y(tb(k),fb(k)) = Y(fb(k),tb(k));
 end
 
 % Formation of Diagonal Elements....
 for m = 1:nb
     for n = 1:nl
         if fb(n) == m
             Y(m,m) = Y(m,m) + y(n)/(a(n)^2) + b(n);
         elseif tb(n) == m
             Y(m,m) = Y(m,m) + y(n) + b(n);
         end
     end
 end
% Y;                  % Bus Admittance Matrix
 %zbus = inv(Y);      % Bus Impedance Matrix